version = 0.1

[production.deploy.parameters]
stack_name = "suthub-prod"
s3_prefix = "suthub-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# These auth parameters will be prompted for during 'sam deploy --guided'
parameter_overrides = "BasicAuthUsername=\"\" BasicAuthPassword=\"\""
resolve_s3 = true
profile = "production"
disable_rollback = true
image_repositories = []

[local.deploy.parameters]
stack_name = "suthub-local"
# ... other local settings if you were to deploy a "dev" stack to AWS (which is probably not going to happen)
