version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "suthub"
s3_bucket = ""
s3_prefix = "suthub"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
resolve_s3 = true
image_repositories = []
