AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-enrollment-poc

  A minimalist Proof of Concept for a serverless enrollment system.

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.9
    Environment:
      Variables:
        AGE_GROUPS_TABLE: !Ref AgeGroupsTable
        ENROLLMENTS_TABLE: !Ref EnrollmentsTable
        ENROLLMENT_QUEUE_URL: !Ref EnrollmentQueue

Resources:
  # API Gateway REST API
  EnrollmentsApi:
    Type: AWS::Serverless::Api # FIX: Changed from HttpApi to Api to support ApiKeyRequired
    Properties:
      StageName: Prod # FIX: Added StageName, which is standard for REST APIs
      # FIX: Add the Auth property here to instruct SAM to create an API Key and Usage Plan.
      # This makes the logical ID 'EnrollmentsApiApiKey' available for the Outputs section.
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API # Creates a single usage plan for the entire API

  # DynamoDB Tables
  AgeGroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  EnrollmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # SQS Queue
  EnrollmentQueue:
    Type: AWS::SQS::Queue

  # --- Lambda Functions ---

  # Age Group Functions
  CreateAgeGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/age_groups/
      Handler: app.create_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgeGroupsTable
      Events:
        ApiEvent:
          Type: Api # FIX: Changed from HttpApi
          Properties:
            Path: /age-groups
            Method: post # FIX: Changed to lowercase for convention, POST is also valid
            RestApiId: !Ref EnrollmentsApi # FIX: Changed from ApiId
            Auth:
              ApiKeyRequired: true # This is now valid

  ListAgeGroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/age_groups/
      Handler: app.list_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AgeGroupsTable
      Events:
        ApiEvent:
          Type: Api # FIX: Changed from HttpApi
          Properties:
            Path: /age-groups
            Method: get # FIX: Changed to lowercase for convention, GET is also valid
            RestApiId: !Ref EnrollmentsApi # FIX: Changed from ApiId
            Auth:
              ApiKeyRequired: true

  DeleteAgeGroupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/age_groups/
      Handler: app.delete_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgeGroupsTable
      Events:
        ApiEvent:
          Type: Api # FIX: Changed from HttpApi
          Properties:
            Path: /age-groups/{id}
            Method: delete # FIX: Changed to lowercase for convention, DELETE is also valid
            RestApiId: !Ref EnrollmentsApi # FIX: Changed from ApiId
            Auth:
              ApiKeyRequired: true

  # Enrollment Functions
  RequestEnrollmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/enrollments/
      Handler: app.request_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AgeGroupsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EnrollmentsTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt EnrollmentQueue.QueueName
      Events:
        ApiEvent:
          Type: Api # FIX: Changed from HttpApi
          Properties:
            Path: /enrollments
            Method: post # FIX: Changed to lowercase for convention, POST is also valid
            RestApiId: !Ref EnrollmentsApi # FIX: Changed from ApiId
            Auth:
              ApiKeyRequired: true

  GetEnrollmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/enrollments/
      Handler: app.get_status_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EnrollmentsTable
      Events:
        ApiEvent:
          Type: Api # FIX: Changed from HttpApi
          Properties:
            Path: /enrollments/{id}
            Method: get # FIX: Changed to lowercase for convention, GET is also valid
            RestApiId: !Ref EnrollmentsApi # FIX: Changed from ApiId
            Auth:
              ApiKeyRequired: true

  # Processor Function
  ProcessEnrollmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/processor/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EnrollmentsTable
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EnrollmentQueue.Arn
            BatchSize: 1

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    # FIX: Updated the URL format for a REST API to include the stage name
    Value: !Sub "https://${EnrollmentsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  ApiKey:
    Description: "API Key for the Enrollment System API"
    # This reference is now valid because we are using AWS::Serverless::Api
    # with ApiKeyRequired set to true. SAM implicitly creates a key with the
    # logical ID {ApiLogicalId}ApiKey.
    Value: !Ref EnrollmentsApiApiKey
